// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PacientService.Data;

#nullable disable

namespace PacientService.Migrations
{
    [DbContext(typeof(PacientDbContext))]
    [Migration("20231002052819_dt")]
    partial class dt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PacientService.Entities.Setups", b =>
                {
                    b.Property<int>("IDALL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDALL"));

                    b.Property<string>("NamenRus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Namenastr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IDALL");

                    b.ToTable("Setups");

                    b.HasData(
                        new
                        {
                            IDALL = 1,
                            NamenRus = "Url для сервиса пациенты",
                            Namenastr = "URL_PACIENT",
                            ValueString = "http://localhost:39289/api/Pacient"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
